AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'lib/protob_pb.rb'
    - 'lib/protob_services_pb.rb'
Style/StringLiterals:
  EnforcedStyle: single_quotes
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
