AllCops:
  NewCops: disable
  TargetRubyVersion: 3.0
  Exclude:
    - 'lib/protob_pb.rb'
    - 'lib/protob_services_pb.rb'
Style/StringLiterals:
  EnforcedStyle: single_quotes
Metrics/AbcSize:
  Exclude:
    - '**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
