# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protob.proto for package 'protob'

require 'grpc'
require 'protob_pb'

module Protob
  module GNFinder
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'protob.GNFinder'

      rpc :Ping, Void, Pong
      rpc :FindNames, Params, NameStrings
    end

    Stub = Service.rpc_stub_class
  end
end
