# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protob.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protob.proto", :syntax => :proto3) do
    add_message "protob.Void" do
    end
    add_message "protob.Pong" do
      optional :value, :string, 1
    end
    add_message "protob.Version" do
      optional :version, :string, 1
      optional :build, :string, 2
    end
    add_message "protob.Params" do
      optional :text, :string, 1
      optional :no_bayes, :bool, 2
      optional :language, :string, 3
      optional :detect_language, :bool, 4
      optional :verification, :bool, 5
      optional :tokens_around, :int32, 6
      repeated :sources, :int32, 7
    end
    add_message "protob.Output" do
      optional :date, :string, 1
      optional :finder_version, :string, 2
      repeated :approach, :enum, 3, "protob.Approach"
      optional :tokens_around, :int32, 4
      optional :language, :string, 5
      optional :language_detected, :string, 6
      optional :detect_language, :bool, 7
      optional :total_tokens, :int32, 8
      optional :total_candidates, :int32, 9
      optional :total_names, :int32, 10
      repeated :names, :message, 11, "protob.NameString"
    end
    add_message "protob.NameString" do
      optional :cardinality, :int32, 1
      optional :verbatim, :string, 3
      optional :name, :string, 4
      optional :odds, :float, 5
      optional :annot_nomen, :string, 6
      optional :annot_nomen_type, :enum, 7, "protob.AnnotNomenType"
      optional :offset_start, :int32, 8
      optional :offset_end, :int32, 9
      repeated :words_before, :string, 10
      repeated :words_after, :string, 11
      optional :verification, :message, 12, "protob.Verification"
    end
    add_message "protob.Verification" do
      optional :best_result, :message, 1, "protob.ResultData"
      repeated :preferred_results, :message, 2, "protob.ResultData"
      optional :data_sources_num, :int32, 3
      optional :data_source_quality, :string, 4
      optional :retries, :int32, 5
      optional :error, :string, 6
    end
    add_message "protob.ResultData" do
      optional :data_source_id, :int32, 1
      optional :data_source_title, :string, 2
      optional :taxon_id, :string, 3
      optional :matched_name, :string, 4
      optional :matched_cardinality, :int32, 5
      optional :matched_canonical_simple, :string, 6
      optional :matched_canonical_full, :string, 7
      optional :current_name, :string, 8
      optional :current_cardinality, :int32, 9
      optional :current_canonical_simple, :string, 10
      optional :current_canonical_full, :string, 11
      optional :synonym, :bool, 12
      optional :classification_path, :string, 13
      optional :classification_rank, :string, 14
      optional :classification_ids, :string, 15
      optional :edit_distance, :int32, 16
      optional :stem_edit_distance, :int32, 17
      optional :match_type, :enum, 18, "protob.MatchType"
    end
    add_enum "protob.MatchType" do
      value :NONE, 0
      value :EXACT, 1
      value :FUZZY, 2
      value :PARTIAL_EXACT, 3
      value :PARTIAL_FUZZY, 4
    end
    add_enum "protob.AnnotNomenType" do
      value :NO_ANNOT, 0
      value :SP_NOV, 1
      value :COMB_NOV, 2
      value :SUBSP_NOV, 3
    end
    add_enum "protob.Approach" do
      value :HEURISTIC, 0
      value :BAYES, 1
    end
  end
end

module Protob
  Void = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.Void").msgclass
  Pong = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.Pong").msgclass
  Version = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.Version").msgclass
  Params = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.Params").msgclass
  Output = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.Output").msgclass
  NameString = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.NameString").msgclass
  Verification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.Verification").msgclass
  ResultData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.ResultData").msgclass
  MatchType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.MatchType").enummodule
  AnnotNomenType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.AnnotNomenType").enummodule
  Approach = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.Approach").enummodule
end
